name: Pull request

on:
  pull_request:
  workflow_dispatch:

jobs:
  # https://github.com/marketplace/actions/paths-changes-filter#examples
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: ./.github/paths-changes-filter.yml
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [changes]
    strategy:
      matrix:
        package-path: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: CI=1 yarn --cwd ${{ matrix.package-path }} test