# based on https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md
name: Release - test, git tag, npm packages
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      ## we don't actually need node because we use a devcontainer below, but this gets npm auth/.npmrc working. 
      ## https://github.com/npm/cli/issues/6184
      #- name: Setup Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: "lts/*"
      #    registry-url: "https://registry.npmjs.org"
      #    always-auth: true
      - run: echo '//registry.yarnpkg.com/:_authToken=${NPM_TOKEN}' > .npmrc
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: yarn release --execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}