name: Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-build:
    # https://github.com/devcontainers/ci/blob/main/docs/github-action.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/erosson/ts-libs
          cacheFrom: ghcr.io/erosson/ts-libs
          push: always
  test:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/erosson/ts-libs
          push: never
          runCmd: yarn test